export const keyMetrics = {
  data: {
    "02/01/2021-02/02/2021": {
      Attributes: null,
      measures: {
        "Page Views": 1793.0,
        Visits: 715.0,
        Visitors: 668.0,
        "Bounce Rate": 70.35,
        "Avg. Time on Site": 527.93,
        "Avg. Visitors per Day": 334.0,
        "Page Views per Visit": 2.51,
        "New Visitors": 541.0,
      },
      SubRows: {
        "02/01/2021": {
          Attributes: null,
          measures: {
            "Page Views": 960.0,
            Visits: 378.0,
            Visitors: 357.0,
            "Bounce Rate": 71.96,
            "Avg. Time on Site": 528.11,
            "Avg. Visitors per Day": 357.0,
            "Page Views per Visit": 2.54,
            "New Visitors": 292.0,
          },
          SubRows: null,
        },
        "02/02/2021": {
          Attributes: null,
          measures: {
            "Page Views": 833.0,
            Visits: 337.0,
            Visitors: 311.0,
            "Bounce Rate": 68.55,
            "Avg. Time on Site": 527.75,
            "Avg. Visitors per Day": 311.0,
            "Page Views per Visit": 2.47,
            "New Visitors": 249.0,
          },
          SubRows: null,
        },
      },
    },
  },
};

const keyMetricsActual = {
  definition: {
    accountID: 1,
    profileID: "rO2MKfYO8k8",
    ID: "rO2MKfYO8k8",
    name: "Webtrends.com  (Copy)  (Copy)",
    language: null,
    type: "profilestats",
    properties: {
      useRealtime: false,
      isSingleBucket: true,
      total_rda_operations: 3,
      total_rda_operations_w_retries: 0,
      total_rda_retries: 0,
    },
    dimension: {
      ID: null,
      name: "Date Range",
      type: "period",
      Range: { startperiod: "1/1/2022", endperiod: "1/5/2022" },
      Properties: null,
      SubDimension: {
        ID: null,
        name: "Date",
        type: "period",
        Range: null,
        Properties: null,
        SubDimension: null,
      },
    },
    measures: [
      {
        name: "Page Views",
        accumulationType: null,
        ID: "PageViews",
        columnID: 0,
        measureFormatType: "numeric",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "Visits",
        accumulationType: null,
        ID: "Visits",
        columnID: 0,
        measureFormatType: "numeric",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "Visitors",
        accumulationType: null,
        ID: "Visitors",
        columnID: 0,
        measureFormatType: "numeric",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "Bounce Rate",
        accumulationType: null,
        ID: "BounceRate",
        columnID: 0,
        measureFormatType: "percent",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "Avg. Time on Site",
        accumulationType: null,
        ID: "AvgTimeOnSite",
        columnID: 0,
        measureFormatType: "time_seconds",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "Avg. Visitors per Day",
        accumulationType: null,
        ID: "AvgVisitorsPerDay",
        columnID: 0,
        measureFormatType: "numeric",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "Page Views per Visit",
        accumulationType: null,
        ID: "PageViewsPerVisit",
        columnID: 0,
        measureFormatType: "numeric",
        AllowTotals: false,
        Sortable: false,
      },
      {
        name: "New Visitors",
        accumulationType: null,
        ID: "NewVisitors",
        columnID: 0,
        measureFormatType: "numeric",
        AllowTotals: false,
        Sortable: false,
      },
    ],
  },
  data: {
    "01/01/2022-01/05/2022": {
      Attributes: null,
      measures: {
        "Page Views": null,
        Visits: null,
        Visitors: null,
        "Bounce Rate": null,
        "Avg. Time on Site": null,
        "Avg. Visitors per Day": null,
        "Page Views per Visit": null,
        "New Visitors": null,
      },
      SubRows: {
        "01/01/2022": null,
        "01/02/2022": null,
        "01/03/2022": null,
        "01/04/2022": null,
        "01/05/2022": null,
      },
    },
  },
};
