export const reports = [
  {
    accountID: 1,
    profileID: null,
    name: "Article Interactions: Department",
    ID: "AjxC2uiVwh8",
    language: null,
    type: null,
    Category: "Social",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Article Interactions",
    ID: "FxWDGyKvwh8",
    language: null,
    type: null,
    Category: "Social",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Blog Interactions",
    ID: "pgXrbzuWwh8",
    language: null,
    type: null,
    Category: "Social",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Breadcrumb: User Login",
    ID: "OIbrLk1hxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Breadcrumb Interactions",
    ID: "tElwQiLixh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Departments: Document File Paths",
    ID: "8ZYzjQGkxh8",
    language: null,
    type: null,
    Category: "People",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Departments: Document Interactions",
    ID: "DVxuAiKkxh8",
    language: null,
    type: null,
    Category: "People",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Departments: Social Interactions",
    ID: "bzklk46Lxh8",
    language: null,
    type: null,
    Category: "People",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document File Paths: Interactions by Departments",
    ID: "OES1Yccjxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document File Paths: Interactions by Job Titles",
    ID: "MroYDk9Kxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document File Paths: Interactions by User Login",
    ID: "ZSr5afdKxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document File Paths Interactions",
    ID: "PwDfuDiKxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document Interactions",
    ID: "QssqfE2kxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document Libraries: Interactions by Document Name",
    ID: "UkU1bvUKxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Document Libraries: Interactions by User Login",
    ID: "Gi8bPuyKxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Documents: Interactions by Departments",
    ID: "JRsbbp7kxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Documents: Interactions by Job Titles",
    ID: "RXc37Xbkxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Documents: Interactions by User Login",
    ID: "RIDZKtDkxh8",
    language: null,
    type: null,
    Category: "Documents",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: City",
    ID: "xOH4TpWLxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: Countries",
    ID: "7ASyiAmlxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: Departments",
    ID: "KMDQZcQlxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: Job Titles",
    ID: "3wbVsxRlxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: Regions",
    ID: "BCQRdLslxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: Site Names",
    ID: "nIxJRNXlxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: States",
    ID: "QvGW1pZlxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Engagement: User Login",
    ID: "wPPPZh1Mxh8",
    language: null,
    type: null,
    Category: "Engagement",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Link Tracking: Destination URLs",
    ID: "MmhXQBiMxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Link Tracking: Link Titles",
    ID: "WQwyJnOMxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Mega Menu: Types",
    ID: "I7Ybxqv9Xh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Mega Menu",
    ID: "TSytOi49Xh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "On-site Search Phrases: Clickthroughs",
    ID: "awvJiZ0mxh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "On-site Search Phrases: Site Names",
    ID: "6aa6FTomxh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "On-site Search Phrases: User Login",
    ID: "z4bvWJVmxh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "On-site Search Phrases",
    ID: "YLDejCXmxh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Experience: Activity",
    ID: "o3uzhW4aXh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Experience: Interactions",
    ID: "CMuZgMpaXh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Experience: Result Clicks by Original Phrase",
    ID: "rNVoKYEbXh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Experience: Session Analysis",
    ID: "HL2YYYpbXh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Experience: Summary",
    ID: "CYeaw5hCXh8",
    language: null,
    type: null,
    Category: "Search",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Name Interactions",
    ID: "m9cUtVANxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Breadcrumbs",
    ID: "LYYtpiGNxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Document File Names",
    ID: "2SWpscpNxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Document File Paths",
    ID: "eOWgIgTNxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Document Libraries",
    ID: "fgFhHIuNxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: List Interactions",
    ID: "jGWOY1Jnxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Newsfeed Interactions",
    ID: "8LbyHepnxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Pages",
    ID: "BBQUE5Vnxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: User Login",
    ID: "vlmr056Oxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Names: Web Parts",
    ID: "QunYzTHOxh8",
    language: null,
    type: null,
    Category: "Sites",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Site Pages: User Login",
    ID: "qp9gfpKTxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "User Drill Down",
    ID: "Fopcweatxh8",
    language: null,
    type: null,
    Category: "People",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Web Parts: Links by Web Parts",
    ID: "ZuUlbghtxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Web Parts: Views by Pages",
    ID: "ITkj6Kwtxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Web Parts: Views by Site Names",
    ID: "5dpU5RBUxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: true,
    IntervalsEnabled: false,
    IsRealtimeCompatible: false,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Web Parts Interactions",
    ID: "UmffBDFUxh8",
    language: null,
    type: null,
    Category: "Content",
    IsHierarchy: false,
    IntervalsEnabled: false,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Pages",
    ID: "18d039ae0360",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Entry Pages",
    ID: "3cc101b982d7",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Exit Pages",
    ID: "430982003855",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Single-Page Visits",
    ID: "82b447d2ae34",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Content Groups",
    ID: "fd33ef1a1e00",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Referring Site",
    ID: "92b64724c3ce",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Referring Domain",
    ID: "6358f2760d94",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Referring Page",
    ID: "2ec502461d94",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Keywords",
    ID: "8ae4a596eb89",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Search Phrases",
    ID: "50ee06302a55",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Top Visitors",
    ID: "4fd174a15bc6",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Domain Names",
    ID: "bb43ad029cae",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Platforms",
    ID: "b0b16301e6c7",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Spiders",
    ID: "7cebb5715501",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Browsers",
    ID: "95df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Browsers by Version",
    ID: "95df19b6d9f3",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Onsite Ad Impressions",
    ID: "39df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Onsite Ad Clickthrough Rates",
    ID: "40df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Onsite Ad Clickthroughs",
    ID: "41df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Cities",
    ID: "42df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Countries",
    ID: "43df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Mobile Devices",
    ID: "44df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
  {
    accountID: 1,
    profileID: null,
    name: "Mobile Browsers",
    ID: "45df19b6d9f2",
    language: null,
    type: null,
    Category: null,
    IsHierarchy: false,
    IntervalsEnabled: true,
    IsRealtimeCompatible: true,
    properties: null,
  },
];
